name: Upload to Firebase App Distribution

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build Politer AI Android mobile application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Generate Release APK
        run: ./gradlew assembleRelease

      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
          token: ${{secrets.FIREBASE_TOKEN}}
          groups: testers
          releaseNotes: "Politer AI Android Application Build"
          file: composeApp/build/outputs/apk/release/composeApp-release-unsigned.apk

